import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({subsets: ['latin'], weight: ['400', '500', '600', '700']})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Yoldi Agency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css"/>
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
